Django/Some models, views, templates and tests/accounts/models.py
import uuid

from django.db import models


class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    full_name = models.CharField(max_length=60)
    phone = models.CharField(max_length=15, blank=True)
    street_address = models.CharField(max_length=250, blank=True)
    apt_number = models.CharField(max_length=4, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    is_email_confirmed = models.BooleanField(default=False)
    activation_key = models.CharField(max_length=16, blank=True)
    password_reset_key = models.CharField(max_length=16, blank=True)
    password_reset_date = models.DateTimeField(null=True, blank=True)
    first_email = models.CharField(max_length=254, blank=True)
    email_change_key = models.CharField(max_length=16, blank=True)
    new_email = models.CharField(max_length=254, blank=True)
    previous_email = models.CharField(max_length=254, blank=True)
    country = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    ip_address = models.GenericIPAddressField(default='0.0.0.0')
    private_notes = models.TextField(blank=True)
    is_deleted = models.BooleanField(default=False)
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

Django/Some models, views, templates and tests/accounts/templates/accounts/auth_base.html
{% extends 'mothership/base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}
{% load exturl from url %}

{#{% block title %}Acme Account{% endblock %}#}

{% block extra_css %}
    {{ block.super }}

    <link href="{% static 'accounts/stylesheets/screen.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section class="hero is-fullheight is-info">
        {% comment %}
        <div class="hero-head">
            <div class="container">
                <div class="tabs is-centered">
                    <ul>
                        <li><a>This is always at the top</a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% endcomment %}

        <div class="hero-body">
            <div class="container has-text-centered">
                {# Make the items inside the centered box left aligned #}
                <a href="{% exturl 'website:home' %}">
                    <img src="{% static 'mothership/images/logo/acme.svg' %}" style="width: 15em">
                </a>

                {# id_title is needed to hide the title from naked_message.html template as they share the same base template #}
                <h1 class="title" id="id_title">
                    {% block title %}{% endblock %}
                </h1>

                {% block body %}{% endblock %}
            </div>
        </div>

        {% comment %}
        <div class="hero-foot">
            <div class="container">
                <div class="tabs is-centered">
                    <ul>
                        <li><a>And this at the bottom</a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% endcomment %}
    </section>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/console_base.html
{% extends 'consoles/base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}

{% block title %}{{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li class="active section">{% trans 'Settings' %}</li>
{% endblock %}

{% block submenu %}
    <nav class="nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a href="{% url 'accounts:profile' %}" class="nav-item is-tab{% if request.path == '/accounts/profile/' %} is-active{% endif %}">
                    {% trans 'Profile' %}
                </a>
                <a href="{% url 'accounts:email' %}" class="nav-item is-tab{% if request.path == '/accounts/email/' %} is-active{% endif %}">
                    {% trans 'Email' %}
                </a>
                <a href="{% url 'accounts:password' %}" class="nav-item is-tab{% if request.path == '/accounts/password/' %} is-active{% endif %}">
                    {% trans 'Password' %}
                </a>
            </div>
        </div>
    </nav>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/email.html
{% extends 'accounts/console_base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}

{% block title %}{{ block.super }}{% trans 'Email' %}{% endblock %}

{% block body %}
    <section class="section">
        <div class="container">
            <h1 class="title">{% trans 'Email' %}</h1>

            <hr>

            {% include 'accounts/forms/email.html' %}
        </div>
    </section>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/login.html
{% extends 'accounts/auth_base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}

{% block title %}{% trans 'Sign into your Acme account' %}{% endblock %}

{% block body %}
    <form action="{{ request.get_full_path }}" method="post">
        {% csrf_token %}

        <div class="columns">
            <div class="column is-one-third is-offset-one-third">
                {% if form.errors or invalid_credentials %}
                    {% trans 'Access Denied' as access_denied %}
                    {% trans 'The provided credentials are invalid.' as invalid_credentials %}

                    {% include 'mothership/message.html' with type='error' heading=True title=access_denied body=invalid_credentials bottom_margin=True %}
                {% endif %}

                {% include 'mothership/forms/field.html' with field=form.email size='medium' icon='envelope-o' labeless=True %}

                <div class="field is-grouped">
                    <p class="control has-icon is-expanded">
                        {{ form.password }}
                        <span class="icon is-medium">
                            <i class="fa fa-key"></i>
                        </span>
                    </p>
                    <p class="control">
                        <a href="{% url 'accounts:recover' %}" class="button is-dark is-medium">
                            {% trans 'Recover' %}
                        </a>
                    </p>
                </div>

                {# {% include 'mothership/forms/field.html' with field=form.password size='medium' icon='key' labeless=True %} #}
            </div>
        </div>

        {% trans 'Log In' as log_in %}
        {% include 'mothership/forms/submit.html' with caption=log_in centered=True synchronous=True %}
    </form>

    <br>

    <p>
        {% trans "Don't have an Acme account?" %}
        <a href="{% url 'accounts:signup' 'organization' %}"><u>{% trans 'Sign up now' %}</u></a>.
    </p>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/password.html
{% extends 'accounts/console_base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}

{% block title %}{{ block.super }}{% trans 'Password' %}{% endblock %}

{% block body %}
    <section class="section">
        <div class="container">
            <h1 class="title">{% trans 'Password' %}</h1>

            <hr>

            {% include 'accounts/forms/password.html' %}
        </div>
    </section>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/profile.html
{% extends 'accounts/console_base.html' %}
{% load trans from i18n %}

{% block title %}{{ block.super }}{% trans 'Profile' %}{% endblock %}

{% block body %}
    <section class="section">
        <div class="container">
            <h1 class="title">{% trans 'Profile' %}</h1>

            <hr>

            {% include 'accounts/forms/profile.html' %}
        </div>
    </section>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/recover.html
{% extends 'accounts/auth_base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}

{% block title %}{% trans 'Recover your account password' %}{% endblock %}

{% block body %}
    <form action="{{ request.get_full_path }}" method="post">
        {% csrf_token %}

        <div class="columns">
            <div class="column is-one-third is-offset-one-third">
                {% if form.errors or invalid_email %}
                    {% trans 'Invalid Submission' as invalid_submission %}
                    {% trans 'Unrecognized email address.' as unrecognized_email_address %}

                    {% include 'mothership/message.html' with type='error' heading=True title=invalid_submission body=unrecognized_email_address bottom_margin=True %}
                {% endif %}

                {% include 'mothership/forms/field.html' with field=form.email size='medium' icon='envelope-o' labeless=True %}
            </div>
        </div>

        {% trans 'Recover' as recover %}
        {% include 'mothership/forms/submit.html' with caption=recover centered=True synchronous=True %}
    </form>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/reset.html
{% extends 'accounts/auth_base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}

{% block title %}{% trans 'Reset your account password' %}{% endblock %}

{% block body %}
    <form action="{{ request.get_full_path }}" method="post">
        {% csrf_token %}

        <div class="columns">
            <div class="column is-one-third is-offset-one-third">
                {% if form.errors or invalid_email %}
                    {% trans 'Invalid Submission' as invalid_submission %}
                    {% trans 'The provided password does not meet requirements.' as requirements_not_met %}

                    {% include 'mothership/message.html' with type='error' heading=True title=invalid_submission body=requirements_not_met bottom_margin=True %}
                {% endif %}

                {% include 'mothership/forms/field.html' with field=form.password size='medium' icon='key' labeless=True %}
            </div>
        </div>

        {% trans 'Change Password' as change_password %}
        {% include 'mothership/forms/submit.html' with caption=change_password centered=True synchronous=True %}
    </form>
{% endblock %}

Django/Some models, views, templates and tests/accounts/templates/accounts/signup.html
{% extends 'accounts/auth_base.html' %}
{% load static from staticfiles %}
{% load trans from i18n %}

{% block title %}{% trans 'Create a new Acme account' %}{% endblock %}

{% block body %}
    <form action="{{ request.get_full_path }}" method="post" class="ui large form">
        {% csrf_token %}

        <div class="columns">
            <div class="column is-one-third is-offset-one-third">
                {% if user_form.errors %}
                    {% trans 'Invalid Submission' as invalid_submission %}
                    {% trans 'Please correct the form below and try again.' as try_again %}

                    {% include 'mothership/message.html' with type='error' heading=True title=invalid_submission body=try_again bottom_margin=True %}
                {% endif %}

                {% if organization_form %}
                    {% include 'mothership/forms/field.html' with field=organization_form.name size='medium' icon='building' labeless=True %}
                {% endif %}
                {% include 'mothership/forms/field.html' with field=profile_form.full_name size='medium' icon='user' labeless=True %}
                {% include 'mothership/forms/field.html' with field=user_form.email size='medium' icon='envelope-o' labeless=True %}
                {% include 'mothership/forms/field.html' with field=user_form.password size='medium' icon='lock' labeless=True %}
            </div>
        </div>

        {% trans 'Create Account' as create_account %}
        {% include 'mothership/forms/submit.html' with caption=create_account centered=True synchronous=True %}
    </form>

    <br>

    <div class="column is-one-third is-offset-one-third">
        <p class="has-text-left">Have an account? <a href="{% url 'accounts:login' %}">{% trans 'Sign in' %}</a>.</p>

        {% ifnotequal request.path '/accounts/signup/owner/' %}
            <p class="has-text-left">{% trans 'Joining an existing organization?' %} <a href="{% url 'accounts:signup' 'personal' %}">{% trans 'Create Personal Account' %}</a>.</p>
        {% endifnotequal %}
    </div>
{% endblock %}

{% block uncompressed_extra_js %}
    {# Don't change this with form autofocus property as it will autoscroll on small mobile devices #}
    <script>
        $(function () {
            {% if organization_form %}
                $('#id_name').focus();
            {% else %}
                $('#id_full_name').focus();
            {% endif %}
        })
    </script>
{% endblock %}